#!/bin/bash

domains=
CERT_EMAIL=

while [ $# -gt 0 ]; do
    case $1
    in
        -d | --domains)
            domains=$2
            shift 2
    ;;
        -e | --email)
            email=$2
            shift 2
    ;;
        *)
            die "Unknown option $1"
    ;;
    esac
done

if [ -z ${domains+x} ]; then
    echo "Need a list of domains!"
    exit 1
fi

DOMAIN_ARR=($(echo ${domains}))

if [[ $email == "" ]]; then
    CERT_EMAIL=admin\@${DOMAIN_ARR[0]}
else
    CERT_EMAIL=$email
fi
echo "Using $CERT_EMAIL as the admin email address."

certbot certonly \
    --quiet \
    --standalone \
    --agree-tos \
    --expand \
    --email $CERT_EMAIL \
    `for domain in ${DOMAIN_ARR[@]}; do echo -n "-d $domain "; done`
