#!/bin/bash


if [ -z $1 ]; then
    echo "Need a domain!"
    exit 1
fi

if [ -z $2 ]; then
    echo "Choose one option to show: key, cert, chain, fullchain"
    exit 1
fi

case $2 in
    key)
        cat /etc/letsencrypt/live/$1/privkey.pem
        ;;
    cert)
        cat /etc/letsencrypt/live/$1/cert.pem
        ;;
    chain)
        cat /etc/letsencrypt/live/$1/chain.pem
        ;;
    fullchain)
        cat /etc/letsencrypt/live/$1/fullchain.pem
        ;;
    *)
        echo "Choose a valid option to show: key, cert, chain, fullchain"
        ;;
esac
