#!/bin/bash

domain=
cert_alias=
passphrase=

while [ $# -gt 0 ]; do
    case $1
    in
        -d | --domain)
            domain=$2
            shift 2
    ;;
        -a | --alias)
            cert_alias=$2
            shift 2
    ;;
        -p | --passphrase)
            passphrase=$2
            shift 2
    ;;
        *)
            die "Unknown option $1"
    ;;
    esac
done

if [ -z "$domain" ]; then
    echo "Need a domain!"
    exit 1
fi

if [ -z "$cert_alias" ]; then
    cert_alias="$domain"
fi

if [ -z "$passphrase" ]; then
    passphrase="changeit"
fi

/usr/local/bin/keytool-import.sh \
    --keystore /keystore \
    --key /etc/letsencrypt/live/$domain/privkey.pem \
    --cert /etc/letsencrypt/live/$domain/cert.pem \
    --cert-chain /etc/letsencrypt/live/$domain/chain.pem \
    --alias "$cert_alias" \
    --passphrase "$passphrase"

keytool -list \
    -keystore /keystore \
    -alias "$cert_alias" \
    -deststorepass "$passphrase"
